Repository fynn-oldenburg/GitHub-Projekt-Wissenschaftliches-Arbeiten, pull requests merged in 2023-02, with the labels that each got.

#49 updated seed
  simulation/simulate.R
  students-data.csv
Labels: enhancement

#47 Use helper cramer in bivariate stats categorical
  functions/analyzing_functions.R
  functions/helper_functions.R
Labels: enhancement

#46 stats_categorical
  functions/analyzing_functions.R
Labels: enhancement

#57 transferred analysis to rmd file
  analysis/analysis.R
  analysis/analysis.rmd
Labels: enhancement

#59 update visualize_categorical documentation
  functions/analyzing_functions.R
Labels: documentation, enhancement

#64 Documentation helper functions
  functions/helper_functions.R
Labels: documentation

#62 Comment of examples in analizing_functions
  functions/analyzing_functions.R
Labels: documentation
